import type { Metadata } from "next";
import "./globals.css";
import { VT323 } from 'next/font/google'

const vt323 = VT323({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: "MozCybeRank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="image.png" type="image/x-icon" />
      </head>
      <body className={vt323.className}>
        {children}
      </body>
    </html>
  );
}
